---
# defaults file for setup_git
git_global_ignore: |
  *~
  .DS_Store

git_configs:
  - name: gitconfig
    path: .gitconfig
    content: |
      [init]
        defaultBranch = main
      [core]
        editor = code --wait --new-window
        excludesfile = /Users/{{ mac_user }}/.gitignore_global
        autocrlf = input
      [diff]
        tool = vscode
      [difftool "vscode"]
        cmd = code --wait --diff $LOCAL $REMOTE
      [merge]
        tool = vscode
      [mergetool "vscode"]
        cmd = code --wait $MERGED
      [difftool "sourcetree"]
        cmd = opendiff \"$LOCAL\" \"$REMOTE\"
        path =
      [mergetool "sourcetree"]
        cmd = /Applications/Sourcetree.app/Contents/Resources/opendiff-w.sh \"$LOCAL\" \"$REMOTE\" -ancestor \"$BASE\" -merge \"$MERGED\"
          trustExitCode = true
      [include]
          path = ~/.gitconfig.unsigned
      [includeIf "gitdir:~/src/private/"]
          path = ~/.gitconfig.personal
      [includeIf "gitdir:/Volumes/sami_ts/src/private/"]
          path = ~/.gitconfig.personal
      [includeIf "gitdir:~/src/orangit/"]
          path = ~/.gitconfig.orangit
      [includeIf "gitdir:/Volumes/sami_ts/src/orangit/"]
          path = ~/.gitconfig.orangit
      [includeIf "gitdir:~/src/customer/"]
          path = ~/.gitconfig.customer
      [includeIf "gitdir:/Volumes/sami_ts/src/customer/"]
          path = ~/.gitconfig.customer
      [includeIf "gitdir:/Volumes/sami_ts/src/assigment/"]
          path = ~/.gitconfig.unsigned
